Add Embed Mode Share Feature
nasa-gibs/worldview pull request #3544
Opened 2021-06-07 19:53 UTC by edplato

## Description

Fixes #964  .

- [x] Add the Embed Mode Feature to allow users to embed Worldview into their webpage and allow their visitors to interact with the Worldview instance they are sharing. 
- [x] Add dynamic A/B dates to Comparison Mode

### Embed Mode:

- Embed share tab will create an `iframe` code block with embedded Worldview that can be copied using copy to clipboard,. A link to additional Embed documentation is provided for further guidance.
- Split the Social Toolbar features and rename as Share Toolbar with Link, Embed, and Social tabs.
- Certain features are disabled, hidden, or removed to focus the embedded Worldview instance to what is being shared. Users can further explore Worldview using the Worldview sidebar logo and the added upper right new tab button, which will both open up a new instance of full production Worldview in a new tab with the same query string parameters used in the embedded instance.
- Embed mode includes an overlay that requires a click to interact in order to prevent unexpected interaction when scrolling down a page using an embedded Worldview page.
- Remove/hide/restyle UI feature styles primarily handled in `embed.css` and `mobile.css` where possible/not conditionally determined within a component.
- Note: ` web/js/containers/sidebar/events.js` is currently filtering events out to 1) only show Events tab if an event is selected and 2) only show selected Event and remove unselect interaction.

### Comparison Mode:

- A/B dates, if different, are now displayed within the individual compare mode UI elements to help users determine what data they’re viewing. If the dates are the same, they are displayed as the currently displayed A/B titles. 
- Style changes have been made to increase unobstructed map area and accommodate date text.

### Additional:

- Create reusable `HoverTooltip` util component
- Revise date text to use `YYYY MMM DD` format for Compare Mode (sidebar and UI modes), Mobile Date Picker, Timeline Axis Date Tooltip, and Timeline Coverage Panel.
- Random spell fixes, updated E2E tests, and refactors.

## How To Test

[Provide whatever information a reviewer might need to know in order to verify that the changes made in this PR are working as expected. If there are special build steps that need to be taken in order to get these changes to run (building while on a separate branch, running `npm ci`, etc) include them here.]

- For bugfixes: What steps need to be taken in the UI to verify the bug is fixed?
- For enhancements and features: What is the expected functionality being added/modified? How can a reviewer verify this?

1. Open with these URL parameters
2. ...
3. Verify expected result

## PR Submission Checklist

This is simply a reminder of what we are going to look for before merging your code.

- I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/main/.github/CONTRIBUTING.md) doc
- I have added necessary documentation (if applicable)
- I have added tests that prove my fix is effective or that my feature works (if applicable)
- Any dependent changes have been merged and published in downstream modules (if applicable)

@nasa-gibs/worldview

2021-06-08 18:01 UTC, minniewong approved these changes
Looks nice and works well! 🚀

2021-06-11 13:16 UTC, jasontk19 requested changes
💯  for a very thorough PR description... it really helps with a diff this large!

Overall this is looking great.  Really like the one-time-format-to-rule-them-all changes and the simplified `HoverTooltip` component.  I just had a few minor suggestions in the code and other observations are listed below:

---

* I don't know if this has changed from `develop` but this modal seems placed a little too far left.  The rest of the toolbar modals open directly underneath their corresponding buttons:
![Screen Shot 2021-06-11 at 8 29 02 AM](https://user-images.githubusercontent.com/1480000/121686578-5cbdaa80-ca8f-11eb-90c7-3b61613e9c09.png)


* It looks like re-ordering layers is disabled but re-ordering groups is not.  I don't know that we _need_ to disable re-ordering groups but just an observation.

* It looks like the GIF creation button is disabled in the animation widget but I didn't see any code handling this in that component so not sure if that's intentional or not?  Seems like making a GIF would be OK in embed mode but might be worth discussion.

2021-06-11 22:51 UTC, rboller commented on doc/embed.md
> +To embed NASA Worldview in your page, navigate to the share toolbar, select the `embed` tab, and copy the code that wraps the current Worldview instance in an `<iframe>` inline element. Add this HTML
Users / embedders may not know what the "share toolbar" is so would suggest rewording to something like, "...click the 'share' button in the upper right corner of the app, select the 'embed' tab..."

2021-06-11 22:54 UTC, rboller commented on web/js/containers/embed.js
> +    const labelText = 'Open new tab with content in Worldview';
This tool tip could use some clarification... something like, "Open this Worldview map in a new window".

2021-06-11 23:03 UTC, rboller approved these changes
Looking great, Ed!    

I've made a few minor comments on different parts of the code and have this one about dates in comparison mode:  if different dates are selected for the A/B opacity slider, the text formatting could be spruced up to provide more visual separation between the "A:" and "B:" labels from their respective dates... e.g.:

**A:**  2021 May 16   ----*--   **B:** 2021 May 19

(though the above doesn't do a whole lot for visual separation with github formatting)

2021-06-16 20:41 UTC, edplato commented on web/js/containers/sidebar/layer-list.js
> +    activeLayers = activeLayers.filter((layer) => layer.visible && layer.layergroup !== 'Reference');
For this case, the reference layer filtering is necessary at the level of the layer-list, but not throughout the entire app.

2021-06-18 19:15 UTC, jasontk19 approved these changes
Looks good!

2021-06-21 15:35 UTC, merged