Wv 2067.2 Updated build status button on README
nasa-gibs/worldview pull request #3780
Opened 2021-12-10 19:46 UTC by jwhurley1

## Description

Updated the image URL for the build status icon in README.md to use the icon provided by GitHub.  The clickthrough URL was updated to the WV GitHub repository.

## PR Submission Checklist

This is simply a reminder of what we are going to look for before merging your code.

- I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/main/.github/CONTRIBUTING.md) doc
- I have added necessary documentation (if applicable)
- I have added tests that prove my fix is effective or that my feature works (if applicable)
- Any dependent changes have been merged and published in downstream modules (if applicable)

@nasa-gibs/worldview

2021-12-10 20:08 UTC, minniewong approved these changes
Looks good. I also tagged Jason K to review

2021-12-10 20:13 UTC, Benjaki2 approved these changes
✅ ✅ ✅

2021-12-10 21:11 UTC, jasontk19 requested changes

2021-12-10 21:11 UTC, jasontk19 commented on README.md
> +[![Build Status](https://github.com/nasa-gibs/worldview/actions/workflows/build-test-app.yml/badge.svg?branch=main)](https://github.com/nasa-gibs/worldview)
Can we have it link to this workflow page instead of the root WV page?

https://github.com/nasa-gibs/worldview/actions/workflows/build-test-app.yml

2021-12-13 15:39 UTC, jasontk19 approved these changes
Looks good!

2021-12-14 17:20 UTC, merged