WV-2178: Eye Icon obscures layer list text in embed mode
nasa-gibs/worldview pull request #3832
Opened 2022-02-23 21:41 UTC by jwhurley1

## Description

Pressing Play for animation in embed mode shows eye icon in layer list and obscures text.  This PR adds an additional class to the `layer-main` div, `layer-visible`, when the `isAnimating` is true.  The CSS in `layer-visible` is only activated when embed mode is active as it is a child of the `.embed-mode` class.

![image](https://user-images.githubusercontent.com/95651563/155409050-486dfe5f-981a-42fd-b354-567b5bb7bd95.png)

## How To Test
1. Open this URL: [localhost](http://localhost:3000/?v=-201.9310639120965,-30.11912669963873,-150.66569698303718,-10.790295040630024&z=4&ics=true&ici=5&icd=10&as=2022-01-15-T04%3A00%3A00Z&ae=2022-01-15-T05%3A20%3A00Z&em=true&l=Coastlines_15m,GOES-West_ABI_GeoColor&lg=true&al=true&ab=on&t=2022-01-15-T04%3A00%3A00Z) and click to interact with the app.
2. Press the play button on the animation menu on the bottom left.
3. The eyeball icon in the layers list should not be overlaying or obscuring the layer information like in the screenshot.

2022-02-23 21:54 UTC, jasontk19 commented
I am not clear on what the desired behavior is or if this fixes it.  These changes appear to cause the eye icon to show and push the layer description contents over.  However, I wasn't sure that the icons were supposed to show at all in embed mode.  Here is the URL i tested with: http://localhost:3000/?v=-189.98423105176428,-38.55893760847881,-162.6125298433694,-2.3504841317899476&z=4&ics=true&ici=5&icd=10&as=2022-01-15-T04%3A00%3A00Z&ae=2022-01-15-T05%3A20%3A00Z&em=true&l=Coastlines_15m,GOES-West_ABI_GeoColor&lg=true&al=true&ab=on&t=2022-01-15-T04%3A00%3A00Z

2022-02-23 21:56 UTC, jasontk19 requested changes
Actually, the ticket indicates that: "the eye icon should not appear in embed mode as you aren't allowed to turn on and off layers in embed mode." so I think this needs to be tweaked

2022-02-23 21:57 UTC, minniewong requested changes
Agree with Jason K's comments - I think the eye should not display at all.

2022-02-23 21:57 UTC, jasontk19 commented on web/js/containers/sidebar/layer-row.js
> +  const getMainLayerClasses = () => (isAnimating ? 'layer-main layer-visible' : 'layer-main');
This could just be a static var instead of a function:  
```const getMainLayerClasses = isAnimating ? 'layer-main layer-visible' : 'layer-main';```

2022-02-24 15:39 UTC, jasontk19 approved these changes
Looks good!

2022-02-24 15:53 UTC, merged