WV-1931: Provide ability to add multiple markers
nasa-gibs/worldview pull request #3841
Opened 2022-03-09 16:53 UTC by jwhurley1

## Description

Provide ability to add multiple markers with labels (using existing ESRI gazetteer labels and coordinates) on the map via right click context menu and are accessible via permalink.

## How To Test
1. Right click anywhere on the map.
2. Select "Add a marker"
3. Add two or three more markers
4. Minimize each marker.
5. Copy coordinates of each marker.
6. Close each marker.

## Acceptance Criteria
1. [ ] Via the right click context menu, a user will be able to add more than one place marker on the map. 
1. [ ] The marker locations are saved in the URL and are accessible via permalink.  

## Some known bugs and TODOs
- Hover tooltips don't seem to disappear after closing or minimizing marker's dialog box. This bug only seems to happen when the hover tooltip is fully opaque.  If closed/minimized during transition, the tooltip closes correctly with dialog box close.
- TODO: Still need to implement URL parameters for each of the markers.

2022-03-09 17:07 UTC, jasontk19 commented
Placing a marker in a polar projection seems to cause an error: 
![Screen Shot 2022-03-09 at 10 04 45 AM](https://user-images.githubusercontent.com/1480000/157493118-ac22f442-cc09-4dd9-9ac4-bd33a919e774.png)

Perhaps related to this issue, markers don't remain showing when switching between projections.  Basically, if I place something in geographic at a latitude where it would be visible in a polar projection, it should still show when I switch to that projection.

2022-03-09 17:12 UTC, jasontk19 commented
Removing a marker from the map _does_ cause it to no longer be visible but, looking in the Redux store it looks like it's just _adding_ a `null` marker rather than removing one from the list.
![Screen Shot 2022-03-09 at 10 11 31 AM](https://user-images.githubusercontent.com/1480000/157494310-6415ae92-1958-4a6c-966f-e12646b43f2a.png)

2022-03-10 22:24 UTC, jwhurley1 commented
> There is a `isCoordinatesDialogOpen` property on `locationSearch` state in the Redux store. Previously this represented whether or not the single location marker had it's tooltip showing. Now that there are multiple, this is no longer valid. I don't see this being used outside of the actions/reducers so we might be able to do away with it, otherwise we may need to store this information per-marker. More investigation is needed.

Still working out the above.

2022-03-15 15:46 UTC, jasontk19 requested changes
I can't seem to place markers any more on this branch.  I get this error:
![Screen Shot 2022-03-15 at 9 45 49 AM](https://user-images.githubusercontent.com/1480000/158416588-aaa0a083-9e69-4d25-8e3d-5286c0ab2373.png)

2022-03-15 15:47 UTC, jwhurley1 commented
> I can't seem to place markers any more on this branch. I get this error: ![Screen Shot 2022-03-15 at 9 45 49 AM](https://user-images.githubusercontent.com/1480000/158416588-aaa0a083-9e69-4d25-8e3d-5286c0ab2373.png)

Yeah I went to check again after our meeting this morning.  Thought it was working when I pushed up yesterday.  I have some changes incoming shortly...

2022-03-17 14:53 UTC, jasontk19 commented
There is an issue with removing markers. To reproduce:

1. Place five location markers
2. Refresh the page
3. Start removing markers
4. At some point, clicking one may remove another or one marker cannot be removed

2022-03-17 15:03 UTC, jasontk19 commented on web/js/map/ui.js
> +    // const coordinatesObject = coordinates.find((element) => element.latitude === results.location.x && element.longitude === results.location.y);
Can remove this commented out code

2022-03-17 15:07 UTC, jasontk19 requested changes
The issue with not being able to remove a marker after page reload seems inconsistent, I will keep trying to see if I can track down why.

2022-03-18 14:57 UTC, jasontk19 commented
There is still an issue removing pins after loading some from a URL and adding more.  See here how only three locations show in the store but there are more on the map.  The ones on the map that aren't showing in the store cannot be removed.
![Screen Shot 2022-03-18 at 8 56 40 AM](https://user-images.githubusercontent.com/1480000/159026988-da2c2d96-2f51-4b9f-90bd-aed0496f6dc7.png)

2022-03-18 15:26 UTC, jasontk19 commented on web/js/components/location-search/coordinates-dialog.js
>            onTouchEnd={this.clearCoordinates}
Place markers can't be removed on mobile and I believe this is why:

It looks like a different function is called `onTouchEnd` for this `span` as compared to the `onClick` for the `<FontAwesomeIcon>` element contained within.  `this.clearCoordinates` is not even defined in this file anymore.  And I think we want to remove the `CLEAR_MARKERS` action/constant/reducer as well as where it's being picked up in `map/ui.js` and causes `removeAllCoordinatesMarkers()` to be called.

2022-03-18 15:26 UTC, jasontk19 commented on web/js/modules/location-search/actions.js
>  export function clearCoordinates() {
This should no longer be needed unless we expect to add functionality to remove all markers at some point.

2022-03-18 16:22 UTC, jasontk19 approved these changes
Looks good, probably just want to rebase with the release branch to get the latest Chromedriver version so the tests can run properly so we can verify they pass before merging.

2022-03-18 17:07 UTC, merged