WV-2587: Fixing Layer Order On Start
nasa-gibs/worldview pull request #4095
Opened 2023-02-08 16:57 UTC by ryanweiler92

## Description

This fixes an issue where the layer groups were being reordered from the permalink. 

## How To Test

1. `git checkout wv-2587-fixing-layer-order`
2. `npm run watch`
3. Load URL `http://localhost:3000/?v=-153.70528206889688,2.910068263484021,-45.19495277801988,56.85125626166882&l=Reference_Labels_15m(hidden),Reference_Features_15m(hidden),OrbitTracks_Sentinel-2A_Descending,OrbitTracks_Sentinel-2B_Descending,OrbitTracks_Landsat-8_Descending(hidden),HLS_S30_Nadir_BRDF_Adjusted_Reflectance,HLS_L30_Nadir_BRDF_Adjusted_Reflectance(hidden),Land_Water_Map&lg=true&t=2021-01-15-T18%3A41%3A50Z`
4. Refresh the page
5. Verify that the layer groups have not been reordered

2023-02-08 17:43 UTC, minniewong requested changes
I found another instance where the ordering on the map was incorrect. 
1. Add Layers --> Land/Water Map then add Fires for Terra
2. See error. Land/Water map is a base layer but appears on top of the fires layer which is an overlay layer.
![Screen Shot 2023-02-08 at 12 43 01 PM](https://user-images.githubusercontent.com/10747923/217609851-c6042b5c-60f5-451e-ba0d-fd877938c2d0.png)

2023-02-09 15:28 UTC, ryanweiler92 commented
> I found another instance where the ordering on the map was incorrect.
> 
> 1. Add Layers --> Land/Water Map then add Fires for Terra
> 2. See error. Land/Water map is a base layer but appears on top of the fires layer which is an overlay layer.
>    ![Screen Shot 2023-02-08 at 12 43 01 PM](https://user-images.githubusercontent.com/10747923/217609851-c6042b5c-60f5-451e-ba0d-fd877938c2d0.png)

I've updated the logic to account for layers with a `layergroup` property of `Reference` and a `group` property of `baselayer` which is only the land water map for now.

2023-02-09 16:08 UTC, minniewong approved these changes
Everything looks good!

2023-02-09 16:55 UTC, Tomcariello approved these changes

2023-02-10 16:14 UTC, ZachTRice approved these changes

2023-02-13 12:47 UTC, merged