WV-2605: Fixing layer ordering in compare mode after removing layers
nasa-gibs/worldview pull request #4106
Opened 2023-02-21 19:07 UTC by ryanweiler92

## Description

This fixes a bug that was causing layers to be added out of order when they were removed while compare mode was active and added again.

## How To Test

1. `git checkout wv-2605` 
2. `npm run watch`
3. Start compare mode
4. Remove all of the layers on compare side A.
5.  Add the Aerosol Optical Depth MODIS/Terra layer.
6. Add the Corrected Reflectance MODIS/Terra layer.
7. Verify that both of these layers are visible on the compare A side and that you can toggle their visibilities.

2023-02-21 20:27 UTC, Tomcariello approved these changes

2023-02-22 19:58 UTC, minniewong requested changes
If you do the steps for the A side - remove all layers, then add AOD, then add Corrected Reflectance (Where the AOD is correctly on top of the corrected reflectance) THEN replicate the same steps for the B side, the layers are also not ordered correctly and an error is returned. 
AssertionError
Call Stack
 Collection.assertUnique_
  wv.js?v=@BUILD_NONCE@:254325:15
 Collection.insertAt
  wv.js?v=@BUILD_NONCE@:254206:12
 addLayer
  wv.js?v=@BUILD_NONCE@:65365:31

2023-02-23 18:28 UTC, ryanweiler92 commented
> If you do the steps for the A side - remove all layers, then add AOD, then add Corrected Reflectance (Where the AOD is correctly on top of the corrected reflectance) THEN replicate the same steps for the B side, the layers are also not ordered correctly and an error is returned. AssertionError Call Stack  Collection.assertUnique_   wv.js?v=@BUILD_NONCE@:254325:15  Collection.insertAt   wv.js?v=@BUILD_NONCE@:254206:12  addLayer   wv.js?v=@BUILD_NONCE@:65365:31

This actually exposed a different bug where the remove group button was dispatching the incorrect action. Instead of utilizing the `removeGroup` action for removing multiple layers, the `removeLayer` action was being used to map through the layers to remove. This was not being relayed correctly to the `removeLayer` component so the layers were being removed from the sidebar but not correctly removed from the open layers map object. I think this fix fits perfectly well in this branch. I have updated the testing description to account for this as well.

2023-02-24 15:52 UTC, minniewong approved these changes
Thanks for working through the bugs!

2023-02-24 21:19 UTC, ZachTRice approved these changes
Working as expected

2023-02-27 13:04 UTC, merged