WV-2642 On mobile, the version/NRT/STD chip is too close to the kebab/three dots
nasa-gibs/worldview pull request #4178
Opened 2023-03-27 18:02 UTC by victorsh

## Description

On mobile, in portrait and landscape modes, the version/NRT/STD chip is too close to the kebab/three dots.
Move the version/NRT/STD chip over so it does not overlap.

Fixes # WV-2642

## How To Test

- `git fetch --all`
- `git checkout wv-2642`
- `npm ci`
- `npm run watch`
- Go to http://localhost:3000 in Chrome
- Open the developer console
- Switch to mobile view
- Click add layer
- Search for `Clear Sky Confidence` and add the layer
- The version/NRT/STD chip should be farther away from the kebab/three dots
<img width="274" alt="Screen Shot 2023-03-27 at 11 01 29 AM" src="https://user-images.githubusercontent.com/5401206/228027460-8ea18596-5391-4a95-9a4a-8789b9fdf8cc.png">

@nasa-gibs/worldview

2023-03-27 19:46 UTC, minniewong requested changes
It looks great on mobile with this PR, but in the desktop view it looks too far from the right.
![Screen Shot 2023-03-27 at 3 44 23 PM](https://user-images.githubusercontent.com/10747923/228049940-9e13f80e-2a65-4ca7-a78f-897690152a94.png)

2023-03-27 20:20 UTC, ryanweiler92 commented
> It looks great on mobile with this PR, but in the desktop view it looks too far from the right. ![Screen Shot 2023-03-27 at 3 44 23 PM](https://user-images.githubusercontent.com/10747923/228049940-9e13f80e-2a65-4ca7-a78f-897690152a94.png)

You're going to want to put the styling in a media query so that it does not affect the desktop view. Once you do that you will also want to check the landscape & tablet views as well.

2023-03-28 13:03 UTC, victorsh commented
@minniewong @ryanweiler92 Added media for landscape and portrait. Desktop is back to normal.
<img width="299" alt="Screen Shot 2023-03-27 at 3 59 21 PM" src="https://user-images.githubusercontent.com/5401206/228086114-aefb2e25-023b-4561-b7d8-e127e1148037.png">
<img width="782" alt="Screen Shot 2023-03-27 at 3 59 06 PM" src="https://user-images.githubusercontent.com/5401206/228086118-0de7090c-cde7-4322-83c8-248119e24ac5.png">
<img width="1032" alt="Screen Shot 2023-03-27 at 3 58 48 PM" src="https://user-images.githubusercontent.com/5401206/228086121-2602d90d-04fd-4ca9-a3f9-53241644bef6.png">

2023-03-28 14:00 UTC, Tomcariello commented
I am seeing the pill still too close to the 3 dots in Firefox (iPhone 12/13 Pro setting).

<img width="813" alt="image" src="https://user-images.githubusercontent.com/19156576/228262485-08186d49-5ae4-4c29-b085-b7a4e3f0f7f8.png">

2023-03-28 14:37 UTC, Tomcariello approved these changes

2023-03-28 16:00 UTC, minniewong approved these changes
Looks great on both mobile and desktop!

2023-03-28 16:52 UTC, merged