WV-2765: Modernizing custom-interval-selector component
nasa-gibs/worldview pull request #4501
Opened 2023-07-17 15:41 UTC by christof-wittreich

## Description
This converts the custom-interval-selector component from a React Class component to a function component, per best modern practices for React. This process included replacing the lifecycle hooks with `useEffect`, and replacing Redux's `connect` with `useSelector` and `useDispatch`.

## How To Test
1. `git checkout wv-2764-modernize-customintervalselector-component`
2. `npm ci`
3. `npm run watch`
4. Locate the custom-interval-selector component in the bottom-left of the screen, as part of the Timeline component.
5. Verify that the new custom-interval-selector component functions the same as the existing custom-interval-selector component.

2023-07-17 18:47 UTC, PatchesMaps approved these changes

2023-07-17 20:02 UTC, Tomcariello approved these changes

2023-07-18 12:38 UTC, ryanweiler92 requested changes
Just for the sake of conciseness we should try to declare our dispatch functions after we declare `const dispatch = useDispatch()`. 

For example, instead of calling `dispatch()` in different functions, we can just write single functions to dispatch our actions like these.

```
  const changeCustomInterval = (delta, timeScale) => dispatch(changeCustomIntervalAction(delta, timeScale));
  const closeModal = () => dispatch(toggleCustomModal(false, undefined));
```

2023-07-18 13:21 UTC, ryanweiler92 approved these changes

2023-07-18 15:50 UTC, merged