wv-2798: Fix references
nasa-gibs/worldview pull request #4620
Opened 2023-08-31 20:13 UTC by Tomcariello

## Description
Point all URLs to production. Information about the existence of non-production instances should not be available publicly. 

Fixes #wv-2798 .

## How To Test
git checkout wv-2798
npm ci
npm install

## Merging

Please use the `squash and merge` commit method unless each commit in your branch is vital to the commit history of main.

@nasa-gibs/worldview

2023-09-05 12:39 UTC, ryanweiler92 requested changes
I'm not sure if this was already discussed but there are a few other references to UAT and SIT in the `toolbar.js` file. We reference WV SIT, WV UAT and GIBS UAT in the requestNotifications function. Removing this will probably disable notifications for SIT and UAT but from the ticket description this seems like it needs to happen regardless. 

Removing these may also require some test e2e or unit tests to be updated but I'm not entirely sure.

2023-09-05 13:07 UTC, Tomcariello commented
> I'm not sure if this was already discussed but there are a few other references to UAT and SIT in the `toolbar.js` file. We reference WV SIT, WV UAT and GIBS UAT in the requestNotifications function. Removing this will probably disable notifications for SIT and UAT but from the ticket description this seems like it needs to happen regardless.
> 
> Removing these may also require some test e2e or unit tests to be updated but I'm not entirely sure.

Yea, there is a discussion about this in Slack (Aug 31st). Solution TBD...

2023-09-05 16:19 UTC, Tomcariello commented
@ryanweiler92 Fix applied to execute the request with less exposure to our test environments in the latest commit.

2023-09-05 17:24 UTC, ryanweiler92 approved these changes

2023-09-08 18:30 UTC, minniewong approved these changes

2023-09-08 19:03 UTC, merged