WV-3117 Charting Feature Styling Updates
nasa-gibs/worldview pull request #5281
Opened 2024-06-12 15:47 UTC by christof-wittreich

## Description
This change updates the styling of the Charting feature in the sidebar of Worldview to match the [wireframes](https://xd.adobe.com/view/1a2a1e24-9231-4d40-8a3c-9055ba9beda1-4f79/). The changes are mostly on the sidebar itself.

## How To Test
1. `git checkout wv-3117-charting-wireframe-implementation`
2. `npm ci`
3. `npm run build`
4. `npm run watch`
5. Open a fresh instance of Worldview.
6. Verify that the default sidebar looks consistent with the wireframes, and that the Charting button is grayed-out.
7. Add a layer with a color palette (Deep Blue Aerosol, Carbon Monoxide L3, etc.) and verify that the Charting button is no longer grayed-out.
8. Click the Charting button and verify that the Charting sidebar interface correctly reflects the wireframes.
9. Ensure that the functionality of the Charting interface still works properly (select date, change area of interest, change between one date and date range, etc.).

2024-07-15 17:12 UTC, minniewong approved these changes

2024-07-16 15:00 UTC, Tomcariello commented
Perhaps outside of the scope of this ticket, but the Charting Tool modal with instructions needs to be updated to reflect the changes made. There is no longer a pencil icon, there is no "Request Chart" button, etc.

2024-07-16 15:07 UTC, Tomcariello commented
Can we put a hover effect on the "Layer" element within the Charting Mode window to display the full layer name? Due to the limited space the layer name may be cut off & we can have very similar layers.

For instance, if I have layers Carbon Monoxide (L2, 500 hPa, Night) & Carbon Monoxide (L2, 500 hPa, Day) the layer is listed as `Carbon Monoxide (L2, 500 hPa, ...`

![image](https://github.com/user-attachments/assets/2c5d6207-8aa6-47aa-8729-d64c46e162dd)

I can also get on board with just removing this entirely since the selected layer is fairly obvious in the layer list above.

2024-07-16 15:17 UTC, Tomcariello commented
I see a few issues with the AOI selection.

- On initially entering charting mode, Generating a chart correctly uses bbox: -90,-180,90,180 for the Entire Screen. 
- Clicking the Entire Screen button presents an AOI widget. Generating a chart (without adjusting the AOI!) still uses bbox: -90,-180,90,180 instead of the coordinates of the AOI.
- Modifying the AOI & then Generating a chart correctly uses the AOI coordinates.
- Clicking the Area of Interest button reverts to the "Entire Screen" mode. However, Generating a chart incorrectly uses the AOI coordinates instead of bbox: -90,-180,90,180.

If I select an AOI & then click the map the AOI disappears & the Area of Interest Indicator reverts to "Entire Screen". Is this the behavior that we want?

2024-07-16 15:27 UTC, Tomcariello commented
I am getting an error when trying to add the Deep Blue Aerosol Type layer from within charting mode. To reproduce:

- Load WV
- Load Carbon Monoxide layer
- Enter Charting mode
- Add Layer Deep Blue Aerosol Type NOAA-20
- Close add layer window
- See `Error VIIRS_Aerosol_Type_Deep_Blue Is not a rendered palette`

I see a bunch of 504 errors in the console that may have something to do with this but I do not see those errors when adding the layer in the normal mode.

2024-07-16 15:29 UTC, Tomcariello commented on web/js/components/charting/chart-component.js
>          <div className="charting-discalimer">
I realize this isn't your error but can we fix this typo?

discalimer --> disclaimer

2024-10-04 20:18 UTC, christof-wittreich commented
This PR will cover fixes for [WV-3274](https://bugs.earthdata.nasa.gov/browse/WV-3274) and [WV-3275](https://bugs.earthdata.nasa.gov/browse/WV-3275). The other review comments will be covered in a later PR

2024-10-08 18:54 UTC, minniewong requested changes
<img width="325" alt="Screenshot 2024-10-08 at 2 53 43 PM" src="https://github.com/user-attachments/assets/32e951bf-9a3b-4fc8-aea8-3b534fb2869e">

Need to update the color/greying out of the "Start Charting" button when you first load Worldview. It's currently so hard to see, I initially didn't think it was there.

2024-10-08 20:53 UTC, minniewong commented
The radio buttons seem excessively large
![Screenshot 2024-10-08 at 4 52 05 PM](https://github.com/user-attachments/assets/f3d1c425-fa5c-4327-8716-90f194f5219e)

2024-10-09 15:26 UTC, minniewong commented
<img width="1591" alt="Screenshot 2024-10-09 at 11 25 47 AM" src="https://github.com/user-attachments/assets/49736ee9-9978-40bb-86f9-d64198c9cd21">

The "One Date" date changer needs more space around it, to match the date range date changer.

2024-10-09 17:56 UTC, christof-wittreich commented
@minniewong Latest commit addresses the 3 changes you commented about, as well as adds the updated text to the charting info popup

2024-10-09 18:42 UTC, minniewong approved these changes

2024-10-16 15:11 UTC, christof-wittreich commented
Added changes to implement [WV-3277](https://bugs.earthdata.nasa.gov/browse/WV-3277) as well. @minniewong @PatchesMaps please take a look

2024-10-16 15:46 UTC, PatchesMaps approved these changes

2024-10-16 16:20 UTC, merged