WV-3210 Distraction Free Timezone Fix
nasa-gibs/worldview pull request #5320
Opened 2024-06-28 20:38 UTC by christof-wittreich

## Description
This change adds logic to the KioskTimeStamp component to correctly list UTC as the timezone when in distraction free mode.

## How To Test
1. `git checkout wv-3210-df-timezone-label`
2. `npm ci`
3. `npm run watch`
4. Open [this link](http://localhost:3000/?v=-263.0855216903962,-171.5672820006298,197.40353620001952,172.94675390257015&z=4&ics=true&ici=5&icd=10&df=true&l=Reference_Labels_15m(hidden),Reference_Features_15m(hidden),Coastlines_15m,GOES-East_ABI_GeoColor,VIIRS_NOAA20_CorrectedReflectance_TrueColor(hidden),VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor&lg=true&t=2024-06-06-T09%3A54%3A00Z) (distraction free mode) and verify that the time is correct and lists it as UTC
5. Open [this link](http://localhost:3000/?v=-263.08552169039626,-171.5672820006298,197.40353620001957,172.94675390257015&z=4&ics=true&ici=5&icd=10&df=true&kiosk=true&l=Reference_Labels_15m(hidden),Reference_Features_15m(hidden),Coastlines_15m,GOES-East_ABI_GeoColor,VIIRS_NOAA20_CorrectedReflectance_TrueColor(hidden),VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor&lg=true&t=2024-06-06-T09%3A54%3A00Z) (kiosk mode) and verify that the change does not affect kiosk mode and it still displays in EDT

2024-06-28 21:08 UTC, PatchesMaps requested changes

2024-06-28 21:08 UTC, PatchesMaps commented on web/js/components/timeline/kiosk-timestamp.js
> +  const timeZoneLabel = updateKioskModeTime ? isDaylightSavingsTime ? 'EDT' : 'EST' : 'UTC';
I'd prefer it if we didn't nest ternary statements. Can we convert this to an if/else block?

2024-07-01 14:45 UTC, PatchesMaps approved these changes

2024-07-01 14:59 UTC, Tomcariello approved these changes

2024-07-01 15:27 UTC, minniewong approved these changes

2024-07-01 15:39 UTC, merged